from __future__ import annotations

from collections import Counter, defaultdict
from pathlib import Path
from typing import Any

from icm_graph_store import load_graph
from icm_graph_validate import validate_graph
from icm_lifecycle import validate_lifecycle
from icm_io import atomic_write_text, safe_repo_path

GENERATED_ROOT = Path(".icm/generated")
GENERATED_HEADER = "<!-- GENERATED BY ICM GRAPH COMPILER. DO NOT EDIT DIRECTLY. -->"


class ProjectionError(ValueError):
    pass


def _index(graph: dict[str, Any]) -> tuple[dict[str, dict[str, Any]], list[dict[str, Any]]]:
    nodes = {
        node["id"]: node
        for node in graph.get("nodes", [])
        if isinstance(node, dict) and isinstance(node.get("id"), str)
    }
    edges = sorted(
        [edge for edge in graph.get("edges", []) if isinstance(edge, dict)],
        key=lambda edge: str(edge.get("id", "")),
    )
    return nodes, edges


def _title(node: dict[str, Any]) -> str:
    return str(node.get("title") or node.get("id") or "Untitled")


def _status(node: dict[str, Any]) -> str:
    value = node.get("status")
    return str(value) if value is not None else "unspecified"


def _front(title: str) -> list[str]:
    return [GENERATED_HEADER, "", f"# {title}", ""]


def _render_graph(graph: dict[str, Any]) -> str:
    nodes, edges = _index(graph)
    lines = _front("ICM Graph Overview")
    type_counts = Counter(str(node.get("type", "unknown")) for node in nodes.values())
    lines.extend(["## Summary", "", f"- nodes: {len(nodes)}", f"- edges: {len(edges)}"])
    for node_type in sorted(type_counts):
        lines.append(f"- {node_type}: {type_counts[node_type]}")

    lines.extend(["", "## Nodes", ""])
    if not nodes:
        lines.append("- none")
    else:
        for node_id in sorted(nodes):
            node = nodes[node_id]
            lines.append(f"- `{node_id}` — {_title(node)} [{_status(node)}]")

    lines.extend(["", "## Edges", ""])
    if not edges:
        lines.append("- none")
    else:
        for edge in edges:
            lines.append(
                f"- `{edge.get('id')}`: `{edge.get('from')}` --{edge.get('type')}--> `{edge.get('to')}`"
            )
    return "\n".join(lines).rstrip() + "\n"


def _render_workflow(graph: dict[str, Any]) -> str:
    nodes, edges = _index(graph)
    execution = {
        node_id: node
        for node_id, node in nodes.items()
        if node.get("type") in {"workflow", "stage", "task"}
    }
    related = [
        edge
        for edge in edges
        if edge.get("from") in execution or edge.get("to") in execution
    ]

    lines = _front("ICM Workflow Projection")
    lines.extend(["## Execution nodes", ""])
    if not execution:
        lines.append("- none")
    else:
        order = {"workflow": 0, "stage": 1, "task": 2}
        for node_id, node in sorted(
            execution.items(),
            key=lambda item: (order.get(str(item[1].get("type")), 9), item[0]),
        ):
            lines.append(
                f"- `{node_id}` ({node.get('type')}) — {_title(node)} [{_status(node)}]"
            )

    lines.extend(["", "## Execution relationships", ""])
    if not related:
        lines.append("- none")
    else:
        for edge in related:
            lines.append(
                f"- `{edge.get('from')}` --{edge.get('type')}--> `{edge.get('to')}`"
            )
    return "\n".join(lines).rstrip() + "\n"


def _render_dependencies(graph: dict[str, Any]) -> str:
    nodes, edges = _index(graph)
    dependency_nodes = {
        node_id: node
        for node_id, node in nodes.items()
        if node.get("type") == "dependency"
    }
    dependency_edges = [
        edge
        for edge in edges
        if edge.get("type") in {"depends_on", "requires"}
        or edge.get("from") in dependency_nodes
        or edge.get("to") in dependency_nodes
    ]

    lines = _front("ICM Dependencies Projection")
    lines.extend(["## Dependency nodes", ""])
    if not dependency_nodes:
        lines.append("- none")
    else:
        for node_id in sorted(dependency_nodes):
            node = dependency_nodes[node_id]
            lines.append(f"- `{node_id}` — {_title(node)} [{_status(node)}]")

    lines.extend(["", "## Dependency relationships", ""])
    if not dependency_edges:
        lines.append("- none")
    else:
        for edge in dependency_edges:
            lines.append(
                f"- `{edge.get('from')}` --{edge.get('type')}--> `{edge.get('to')}`"
            )
    return "\n".join(lines).rstrip() + "\n"


def _render_protected_state(graph: dict[str, Any]) -> str:
    nodes, edges = _index(graph)
    protected = {
        node_id: node
        for node_id, node in nodes.items()
        if node.get("type") == "protected_resource"
    }
    related = [
        edge
        for edge in edges
        if edge.get("from") in protected
        or edge.get("to") in protected
        or edge.get("type") == "protects"
    ]

    lines = _front("ICM Protected State Projection")
    lines.extend(["## Protected resources", ""])
    if not protected:
        lines.append("- none")
    else:
        for node_id in sorted(protected):
            node = protected[node_id]
            policy = node.get("attributes", {}).get("policy", "unspecified")
            path = node.get("attributes", {}).get("path", "unspecified")
            lines.append(
                f"- `{node_id}` — {_title(node)}; policy=`{policy}`; path=`{path}`"
            )

    lines.extend(["", "## Protection relationships", ""])
    if not related:
        lines.append("- none")
    else:
        for edge in related:
            lines.append(
                f"- `{edge.get('from')}` --{edge.get('type')}--> `{edge.get('to')}`"
            )
    return "\n".join(lines).rstrip() + "\n"


def _terminal_execution(node: dict[str, Any]) -> bool:
    node_type = node.get("type")
    status = node.get("status")
    terminal = {
        "workflow": {"certified", "completed"},
        "stage": {"certified"},
        "task": {"completed", "certified"},
    }
    return status in terminal.get(node_type, set())


def _operational_snapshot(graph: dict[str, Any]) -> dict[str, Any]:
    nodes, edges = _index(graph)
    execution = {
        node_id: node
        for node_id, node in nodes.items()
        if node.get("type") in {"workflow", "stage", "task"}
    }

    incoming_dependencies: dict[str, list[str]] = defaultdict(list)
    blockers: dict[str, list[str]] = defaultdict(list)
    for edge in edges:
        edge_type = edge.get("type")
        source = edge.get("from")
        target = edge.get("to")
        if edge_type == "depends_on" and source in execution and target in execution:
            incoming_dependencies[str(source)].append(str(target))
        if edge_type == "blocks" and target in execution:
            source_node = nodes.get(source)
            if source_node is None:
                continue
            source_status = source_node.get("status")
            source_type = source_node.get("type")
            resolved = (
                _terminal_execution(source_node)
                if source_type in {"workflow", "stage", "task"}
                else source_status in {"resolved", "closed"}
            )
            if not resolved:
                blockers[str(target)].append(str(source))

    active = sorted(
        node_id for node_id, node in execution.items()
        if node.get("status") in {"active", "blocked", "stale"}
    )
    pending = sorted(
        node_id for node_id, node in execution.items()
        if node.get("status") in {"planned", "pending"}
    )
    next_actionable: list[str] = []
    for node_id in pending:
        deps = incoming_dependencies.get(node_id, [])
        if blockers.get(node_id):
            continue
        if all(_terminal_execution(execution[dep]) for dep in deps if dep in execution):
            next_actionable.append(node_id)

    unresolved = sorted(
        node_id for node_id, node in nodes.items()
        if node.get("type") == "unresolved"
    )
    decisions = sorted(
        node_id for node_id, node in nodes.items()
        if node.get("type") == "decision" and node.get("status") != "superseded"
    )
    protected = sorted(
        node_id for node_id, node in nodes.items()
        if node.get("type") == "protected_resource"
    )
    pull_requests = sorted(
        node_id for node_id, node in nodes.items()
        if node.get("type") == "pull_request" and node.get("status") not in {"merged", "closed"}
    )
    actors = sorted(
        node_id for node_id, node in nodes.items()
        if node.get("type") == "actor"
    )

    satisfied: set[str] = set()
    for edge in edges:
        if edge.get("type") not in {"satisfies", "validates"}:
            continue
        source = nodes.get(edge.get("from"))
        target = nodes.get(edge.get("to"))
        if source and target and source.get("type") == "evidence" and target.get("type") == "acceptance_criterion":
            satisfied.add(str(target.get("id")))
    unsatisfied_acceptance = sorted(
        node_id for node_id, node in nodes.items()
        if node.get("type") == "acceptance_criterion" and node_id not in satisfied
    )

    return {
        "nodes": nodes,
        "active": active,
        "pending": pending,
        "next_actionable": next_actionable,
        "blockers": {key: sorted(value) for key, value in sorted(blockers.items())},
        "unresolved": unresolved,
        "decisions": decisions,
        "protected": protected,
        "pull_requests": pull_requests,
        "actors": actors,
        "unsatisfied_acceptance": unsatisfied_acceptance,
    }


def _bounded_items(items: list[str], *, limit: int = 20) -> tuple[list[str], int]:
    shown = items[:limit]
    return shown, max(0, len(items) - len(shown))


def _append_node_list(lines: list[str], heading: str, ids: list[str], nodes: dict[str, dict[str, Any]]) -> None:
    lines.extend(["", f"## {heading}", ""])
    shown, omitted = _bounded_items(ids)
    if not shown:
        lines.append("- none")
    else:
        for node_id in shown:
            node = nodes.get(node_id, {})
            lines.append(f"- `{node_id}` — {_title(node)} [{_status(node)}]")
        if omitted:
            lines.append(f"- ... {omitted} more")


def _render_status(graph: dict[str, Any]) -> str:
    snapshot = _operational_snapshot(graph)
    nodes = snapshot["nodes"]
    lines = _front("ICM Status")
    lines.extend([
        "## Summary",
        "",
        f"- active_or_blocked_or_stale: {len(snapshot['active'])}",
        f"- pending: {len(snapshot['pending'])}",
        f"- next_actionable: {len(snapshot['next_actionable'])}",
        f"- unresolved: {len(snapshot['unresolved'])}",
        f"- unsatisfied_acceptance: {len(snapshot['unsatisfied_acceptance'])}",
        f"- protected_resources: {len(snapshot['protected'])}",
        f"- open_pull_requests: {len(snapshot['pull_requests'])}",
    ])
    _append_node_list(lines, "Active / blocked / stale", snapshot["active"], nodes)
    _append_node_list(lines, "Next actionable", snapshot["next_actionable"], nodes)
    _append_node_list(lines, "Unresolved", snapshot["unresolved"], nodes)
    _append_node_list(lines, "Unsatisfied acceptance", snapshot["unsatisfied_acceptance"], nodes)
    return "\n".join(lines).rstrip() + "\n"


def _render_handoff(graph: dict[str, Any]) -> str:
    snapshot = _operational_snapshot(graph)
    nodes = snapshot["nodes"]
    lines = _front("ICM Graph Handoff")
    lines.extend([
        "Canonical machine state: `.icm/graph/`",
        "",
        "This is a generated bounded state transfer, not a diary.",
    ])
    _append_node_list(lines, "Current execution", snapshot["active"], nodes)
    _append_node_list(lines, "Next actionable", snapshot["next_actionable"], nodes)
    _append_node_list(lines, "Unresolved", snapshot["unresolved"], nodes)
    _append_node_list(lines, "Open pull requests", snapshot["pull_requests"], nodes)
    _append_node_list(lines, "Responsible actors", snapshot["actors"], nodes)
    _append_node_list(lines, "Active decisions", snapshot["decisions"], nodes)
    _append_node_list(lines, "Protected resources", snapshot["protected"], nodes)
    _append_node_list(lines, "Unsatisfied acceptance", snapshot["unsatisfied_acceptance"], nodes)

    lines.extend(["", "## Live blockers", ""])
    blocker_rows = [
        (target, blocker)
        for target, blockers in snapshot["blockers"].items()
        for blocker in blockers
    ]
    if not blocker_rows:
        lines.append("- none")
    else:
        shown, omitted = _bounded_items([f"{target} <- {blocker}" for target, blocker in blocker_rows])
        for value in shown:
            target, blocker = value.split(" <- ", 1)
            lines.append(f"- `{target}` blocked by `{blocker}`")
        if omitted:
            lines.append(f"- ... {omitted} more")
    return "\n".join(lines).rstrip() + "\n"


def _operational_diagnostics(root: Path, graph: dict[str, Any]) -> list[dict[str, str]]:
    return validate_graph(root, graph) + validate_lifecycle(graph)


def _require_operationally_renderable(root: Path, graph: dict[str, Any], view: str) -> None:
    diagnostics = _operational_diagnostics(root, graph)
    failures = [item for item in diagnostics if item.get("severity") == "FAIL"]
    if failures:
        summary = "; ".join(f"{item['code']}:{item['subject']}" for item in failures[:5])
        raise ProjectionError(f"refusing to render {view} from invalid operational graph: {summary}")


def render_status(root: Path, graph: dict[str, Any] | None = None) -> str:
    if graph is None:
        graph = load_graph(root)
    _require_operationally_renderable(root, graph, "status")
    return _render_status(graph)


def render_handoff(root: Path, graph: dict[str, Any] | None = None) -> str:
    if graph is None:
        graph = load_graph(root)
    _require_operationally_renderable(root, graph, "handoff")
    return _render_handoff(graph)


def render_projections(root: Path, graph: dict[str, Any] | None = None) -> dict[str, str]:
    if graph is None:
        graph = load_graph(root)
    _require_operationally_renderable(root, graph, "projection bundle")

    return {
        "GRAPH.md": _render_graph(graph),
        "WORKFLOW.md": _render_workflow(graph),
        "DEPENDENCIES.md": _render_dependencies(graph),
        "PROTECTED_STATE.md": _render_protected_state(graph),
        "STATUS.md": _render_status(graph),
        "HANDOFF.md": _render_handoff(graph),
    }


def write_projections(root: Path, graph: dict[str, Any] | None = None) -> list[str]:
    rendered = render_projections(root, graph)
    target = safe_repo_path(root, GENERATED_ROOT)
    target.mkdir(parents=True, exist_ok=True)
    changed: list[str] = []
    for name in sorted(rendered):
        path = target / name
        content = rendered[name]
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == content:
            continue
        atomic_write_text(path, content)
        changed.append(str(path.relative_to(root)))
    return changed
